### ISSUE TITLE
Issues on Windows

### ISSUE THREAD

**Issue by jensontech** [kanej/lein-s3-sync#4]
I am trying to use lein-s3-sync in a Windows environment.

My `project.clj` includes -
`:s3-sync {:access-key ~(System/getenv "AWS_ACCESS_KEY_ID")
            :secret-key ~(System/getenv "AWS_SECRET_ACCESS_KEY")
            :local-dir  "resources/public/compiled_prod"
            :bucket     "abucketname"}`
Using version "0.2.0" I get 
`>lein s3-sync
Deploying ./resources/public/compiled_prod/ to abucketname
java.util.regex.PatternSyntaxException: Illegal/unsupported escape sequence near....`
The path displayed has backslashes. The string at the position reported is "\C". 

Using version "0.3.0" I get 
`>lein s3-sync
Syncing bucket abucketname with directory resources/public/compiled_prod
clojure.lang.ArityException: Wrong number of args (4) passed to: s3-sync/sync-to-s3
 at clojure.lang.AFn.throwArity (AFn.java:429)`

Any chance of a fix?

**Comment by kanej** [comment]
Could you try with the latest version of lein-s3-sync `0.4.0`? I have been able to use it successfully from windows as it includes the changes that @arosequist kindly made.
