### ISSUE TITLE
Add metadata to S3 options

### ISSUE THREAD

**Issue by currentoor** [kanej/lein-s3-sync#7]
I'd like to send some metadata to S3, in addition to whether or not the resource is public.

Something like
```clj
(me.kanej.s3-sync/sync-to-s3 cred dir-path bucket-name
                             {:public   true
                              :metadata {:cache-control "public, max-age=31536000"}})
```

Seems like it should be an easy addition. Would you accept a pull request?

**Comment by kanej** [comment]
Definitely
