### ISSUE TITLE
Add permissions to S3 options

### ISSUE THREAD

**Issue by splayemu** [kanej/lein-s3-sync#9]
Hello,

I was curious if you would be open to a PR to add permissions to the S3 options. We sometimes get a race condition between the following two api calls. If we can send the public permission in the initial `put-file`, the race condition should go away.

```
          (s3/put-file
            aws-credentials
            bucket-name
            rel-path
            (fs/combine-path local-dir rel-path)
            (:metadata options))

          (when (:public options)
            (s3/make-file-public aws-credentials bucket-name rel-path))
```

**Comment by kanej** [comment]
Definitely, happy to look over a PR and get it merged in
